#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_user:
  path: /
  controller: App\Controller\HomeController::user

home_admin:
  path: /admin
  controller: App\Controller\HomeController::admin

comments:
  path: /admin/comments/page/{page}
  controller: App\Controller\CommentController::index

comments_create:
  path: /posts/{slug}/comments/create
  controller: App\Controller\CommentController::create

comments_valid:
  path: /admin/comments/{id}/valid
  controller: App\Controller\CommentController::valid

comments_delete:
  path: /admin/comments/{id}/delete
  controller: App\Controller\CommentController::delete

comments_show:
  path: /admin/comments/{id}
  controller: App\Controller\CommentController::show

posts_create:
  path: /admin/posts/create
  controller: App\Controller\PostController::create

posts_edit:
  path: /admin/posts/edit/{id}
  controller: App\Controller\PostController::edit

posts_delete:
  path: /admin/posts/delete/{id}
  controller: App\Controller\PostController::delete

posts_admin:
  path: admin/posts/page/{page}
  controller: App\Controller\PostController::admin

posts:
  path: /posts/page/{page}
  controller: App\Controller\PostController::index
posts_show:
  path: /posts/{slug}
  controller: App\Controller\PostController::show
#  requirements:
#    page: '\d+'

categories:
  path: /admin/categories/
  controller: App\Controller\CategoryController::index

categories_create:
  path: /admin/categories/create
  controller: App\Controller\CategoryController::create

categories_edit:
  path: /admin/categories/edit/{id}
  controller: App\Controller\CategoryController::edit

categories_delete:
  path: /admin/categories/delete/{id}
  controller: App\Controller\CategoryController::delete
